/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const Booking = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'cancelled' : IDL.Null,
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'rejected' : IDL.Null,
  }),
  'endDate' : Time,
  'propertyId' : IDL.Nat,
  'userDetails' : IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'phone' : IDL.Text,
  }),
  'propertyIdText' : IDL.Text,
  'student' : IDL.Principal,
  'stripeSessionId' : IDL.Opt(IDL.Text),
  'totalPrice' : IDL.Nat,
  'startDate' : Time,
});
export const ShoppingItem = IDL.Record({
  'productName' : IDL.Text,
  'currency' : IDL.Text,
  'quantity' : IDL.Nat,
  'priceInCents' : IDL.Nat,
  'productDescription' : IDL.Text,
});
export const Announcement = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'expiresAt' : IDL.Opt(Time),
  'createdAt' : Time,
  'isActive' : IDL.Bool,
  'message' : IDL.Text,
});
export const Inquiry = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'pending' : IDL.Null,
    'rejected' : IDL.Null,
    'accepted' : IDL.Null,
  }),
  'studentName' : IDL.Text,
  'inquiryType' : IDL.Variant({
    'bookVisit' : IDL.Null,
    'contactOwner' : IDL.Null,
  }),
  'studentPrincipal' : IDL.Principal,
  'studentPhone' : IDL.Text,
  'propertyId' : IDL.Nat,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Address = IDL.Record({
  'blocknumber' : IDL.Text,
  'street' : IDL.Text,
  'country' : IDL.Text,
  'city' : IDL.Text,
  'state' : IDL.Text,
  'bluenumber' : IDL.Text,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Coordinates = IDL.Record({ 'lat' : IDL.Text, 'lang' : IDL.Text });
export const Property = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'verified' : IDL.Bool,
  'owner' : IDL.Principal,
  'description' : IDL.Text,
  'amenities' : IDL.Vec(IDL.Text),
  'availableFrom' : Time,
  'viewCount' : IDL.Nat,
  'approved' : IDL.Bool,
  'genderPreference' : IDL.Variant({
    'boys' : IDL.Null,
    'unisex' : IDL.Null,
    'girls' : IDL.Null,
  }),
  'address' : Address,
  'pricePerMonth' : IDL.Nat,
  'roomType' : IDL.Variant({
    'apartment' : IDL.Null,
    'sharedRoom' : IDL.Null,
    'single' : IDL.Null,
  }),
  'photos' : IDL.Vec(ExternalBlob),
  'coordinates' : Coordinates,
  'contactPhone' : IDL.Text,
});
export const UserProfile = IDL.Record({
  'name' : IDL.Text,
  'role' : IDL.Variant({
    'admin' : IDL.Null,
    'owner' : IDL.Null,
    'student' : IDL.Null,
  }),
  'email' : IDL.Text,
  'phone' : IDL.Text,
});
export const Notification = IDL.Record({
  'id' : IDL.Nat,
  'ownerPrincipal' : IDL.Principal,
  'relatedInquiryId' : IDL.Opt(IDL.Nat),
  'isRead' : IDL.Bool,
  'message' : IDL.Text,
  'timestamp' : Time,
});
export const Report = IDL.Record({
  'id' : IDL.Nat,
  'status' : IDL.Variant({
    'resolved' : IDL.Null,
    'pending' : IDL.Null,
    'dismissed' : IDL.Null,
  }),
  'targetPropertyId' : IDL.Nat,
  'description' : IDL.Text,
  'reporterId' : IDL.Principal,
  'timestamp' : Time,
  'actionTaken' : IDL.Opt(IDL.Text),
  'reason' : IDL.Text,
});
export const Review = IDL.Record({
  'propertyId' : IDL.Nat,
  'comment' : IDL.Text,
  'timestamp' : Time,
  'student' : IDL.Principal,
  'rating' : IDL.Nat,
});
export const StripeSessionStatus = IDL.Variant({
  'completed' : IDL.Record({
    'userPrincipal' : IDL.Opt(IDL.Text),
    'response' : IDL.Text,
  }),
  'failed' : IDL.Record({ 'error' : IDL.Text }),
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});
export const StripeConfiguration = IDL.Record({
  'allowedCountries' : IDL.Vec(IDL.Text),
  'secretKey' : IDL.Text,
});
export const http_header = IDL.Record({
  'value' : IDL.Text,
  'name' : IDL.Text,
});
export const http_request_result = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});
export const TransformationInput = IDL.Record({
  'context' : IDL.Vec(IDL.Nat8),
  'response' : http_request_result,
});
export const TransformationOutput = IDL.Record({
  'status' : IDL.Nat,
  'body' : IDL.Vec(IDL.Nat8),
  'headers' : IDL.Vec(http_header),
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
  'addToWishlist' : IDL.Func([IDL.Nat], [], []),
  'approveProperty' : IDL.Func([IDL.Nat], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'blockUser' : IDL.Func([IDL.Principal], [], []),
  'bookProperty' : IDL.Func([Booking], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'rejectBooking' : IDL.Func([IDL.Nat], [], []),
  'createAnnouncement' : IDL.Func([IDL.Text, IDL.Text, IDL.Opt(Time)], [], []),
  'createCheckoutSession' : IDL.Func(
      [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
      [IDL.Text],
      [],
    ),
  'createInquiry' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Text,
        IDL.Variant({ 'bookVisit' : IDL.Null, 'contactOwner' : IDL.Null }),
        IDL.Text,
      ],
      [],
      [],
    ),
  'deactivateAnnouncement' : IDL.Func([IDL.Nat], [], []),
  'deleteProperty' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
  'dismissReport' : IDL.Func([IDL.Nat], [], []),
  'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getAnalyticsSummary' : IDL.Func(
      [],
      [
        IDL.Record({
          'pendingListings' : IDL.Nat,
          'totalProperties' : IDL.Nat,
          'activeListings' : IDL.Nat,
          'totalReports' : IDL.Nat,
          'totalBookings' : IDL.Nat,
          'totalUsers' : IDL.Nat,
          'totalInquiries' : IDL.Nat,
        }),
      ],
      ['query'],
    ),
  'getApprovedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getDailyActiveUserCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat }))],
      ['query'],
    ),
  'getOwnerInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getOwnerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
  'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
  'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
  'getPropertyBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
  'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
  'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
  'getStripePayments' : IDL.Func([], [IDL.Text], []),
  'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
  'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
  'getUserBookings' : IDL.Func([IDL.Principal], [IDL.Vec(Booking)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
  'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'listProperty' : IDL.Func([Property], [], []),
  'markAllNotificationsRead' : IDL.Func([], [], []),
  'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
  'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
  'requestApproval' : IDL.Func([], [], []),
  'resolveReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
  'submitReport' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
  'trackActivity' : IDL.Func([], [], []),
  'trackPropertyView' : IDL.Func([IDL.Nat], [], []),
  'transform' : IDL.Func(
      [TransformationInput],
      [TransformationOutput],
      ['query'],
    ),
  'unblockUser' : IDL.Func([IDL.Principal], [], []),
  'updateInquiryStatus' : IDL.Func(
      [IDL.Nat, IDL.Variant({ 'rejected' : IDL.Null, 'accepted' : IDL.Null })],
      [],
      [],
    ),
  'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
  'verifyProperty' : IDL.Func([IDL.Nat], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const Booking = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'cancelled' : IDL.Null,
      'pending' : IDL.Null,
      'paid' : IDL.Null,
      'rejected' : IDL.Null,
    }),
    'endDate' : Time,
    'propertyId' : IDL.Nat,
    'userDetails' : IDL.Record({
      'name' : IDL.Text,
      'email' : IDL.Text,
      'phone' : IDL.Text,
    }),
    'propertyIdText' : IDL.Text,
    'student' : IDL.Principal,
    'stripeSessionId' : IDL.Opt(IDL.Text),
    'totalPrice' : IDL.Nat,
    'startDate' : Time,
  });
  const ShoppingItem = IDL.Record({
    'productName' : IDL.Text,
    'currency' : IDL.Text,
    'quantity' : IDL.Nat,
    'priceInCents' : IDL.Nat,
    'productDescription' : IDL.Text,
  });
  const Announcement = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'expiresAt' : IDL.Opt(Time),
    'createdAt' : Time,
    'isActive' : IDL.Bool,
    'message' : IDL.Text,
  });
  const Inquiry = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'pending' : IDL.Null,
      'rejected' : IDL.Null,
      'accepted' : IDL.Null,
    }),
    'studentName' : IDL.Text,
    'inquiryType' : IDL.Variant({
      'bookVisit' : IDL.Null,
      'contactOwner' : IDL.Null,
    }),
    'studentPrincipal' : IDL.Principal,
    'studentPhone' : IDL.Text,
    'propertyId' : IDL.Nat,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Address = IDL.Record({
    'blocknumber' : IDL.Text,
    'street' : IDL.Text,
    'country' : IDL.Text,
    'city' : IDL.Text,
    'state' : IDL.Text,
    'bluenumber' : IDL.Text,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Coordinates = IDL.Record({ 'lat' : IDL.Text, 'lang' : IDL.Text });
  const Property = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'verified' : IDL.Bool,
    'owner' : IDL.Principal,
    'description' : IDL.Text,
    'amenities' : IDL.Vec(IDL.Text),
    'availableFrom' : Time,
    'viewCount' : IDL.Nat,
    'approved' : IDL.Bool,
    'genderPreference' : IDL.Variant({
      'boys' : IDL.Null,
      'unisex' : IDL.Null,
      'girls' : IDL.Null,
    }),
    'address' : Address,
    'pricePerMonth' : IDL.Nat,
    'roomType' : IDL.Variant({
      'apartment' : IDL.Null,
      'sharedRoom' : IDL.Null,
      'single' : IDL.Null,
    }),
    'photos' : IDL.Vec(ExternalBlob),
    'coordinates' : Coordinates,
    'contactPhone' : IDL.Text,
  });
  const UserProfile = IDL.Record({
    'name' : IDL.Text,
    'role' : IDL.Variant({
      'admin' : IDL.Null,
      'owner' : IDL.Null,
      'student' : IDL.Null,
    }),
    'email' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Notification = IDL.Record({
    'id' : IDL.Nat,
    'ownerPrincipal' : IDL.Principal,
    'relatedInquiryId' : IDL.Opt(IDL.Nat),
    'isRead' : IDL.Bool,
    'message' : IDL.Text,
    'timestamp' : Time,
  });
  const Report = IDL.Record({
    'id' : IDL.Nat,
    'status' : IDL.Variant({
      'resolved' : IDL.Null,
      'pending' : IDL.Null,
      'dismissed' : IDL.Null,
    }),
    'targetPropertyId' : IDL.Nat,
    'description' : IDL.Text,
    'reporterId' : IDL.Principal,
    'timestamp' : Time,
    'actionTaken' : IDL.Opt(IDL.Text),
    'reason' : IDL.Text,
  });
  const Review = IDL.Record({
    'propertyId' : IDL.Nat,
    'comment' : IDL.Text,
    'timestamp' : Time,
    'student' : IDL.Principal,
    'rating' : IDL.Nat,
  });
  const StripeSessionStatus = IDL.Variant({
    'completed' : IDL.Record({
      'userPrincipal' : IDL.Opt(IDL.Text),
      'response' : IDL.Text,
    }),
    'failed' : IDL.Record({ 'error' : IDL.Text }),
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  const StripeConfiguration = IDL.Record({
    'allowedCountries' : IDL.Vec(IDL.Text),
    'secretKey' : IDL.Text,
  });
  const http_header = IDL.Record({ 'value' : IDL.Text, 'name' : IDL.Text });
  const http_request_result = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  const TransformationInput = IDL.Record({
    'context' : IDL.Vec(IDL.Nat8),
    'response' : http_request_result,
  });
  const TransformationOutput = IDL.Record({
    'status' : IDL.Nat,
    'body' : IDL.Vec(IDL.Nat8),
    'headers' : IDL.Vec(http_header),
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addReview' : IDL.Func([IDL.Nat, IDL.Nat, IDL.Text], [], []),
    'addToWishlist' : IDL.Func([IDL.Nat], [], []),
    'approveProperty' : IDL.Func([IDL.Nat], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'blockUser' : IDL.Func([IDL.Principal], [], []),
    'bookProperty' : IDL.Func([Booking], [], []),
  'cancelBooking' : IDL.Func([IDL.Nat], [], []),
  'confirmBooking' : IDL.Func([IDL.Nat], [], []),
  'rejectBooking' : IDL.Func([IDL.Nat], [], []),
    'createAnnouncement' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Opt(Time)],
        [],
        [],
      ),
    'createCheckoutSession' : IDL.Func(
        [IDL.Vec(ShoppingItem), IDL.Text, IDL.Text],
        [IDL.Text],
        [],
      ),
    'createInquiry' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Text,
          IDL.Variant({ 'bookVisit' : IDL.Null, 'contactOwner' : IDL.Null }),
          IDL.Text,
        ],
        [],
        [],
      ),
    'deactivateAnnouncement' : IDL.Func([IDL.Nat], [], []),
    'deleteProperty' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Nat, IDL.Principal], [], []),
    'dismissReport' : IDL.Func([IDL.Nat], [], []),
    'getActiveAnnouncements' : IDL.Func([], [IDL.Vec(Announcement)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getAnalyticsSummary' : IDL.Func(
        [],
        [
          IDL.Record({
            'pendingListings' : IDL.Nat,
            'totalProperties' : IDL.Nat,
            'activeListings' : IDL.Nat,
            'totalReports' : IDL.Nat,
            'totalBookings' : IDL.Nat,
            'totalUsers' : IDL.Nat,
            'totalInquiries' : IDL.Nat,
          }),
        ],
        ['query'],
      ),
    'getApprovedProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getDailyActiveUserCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Record({ 'date' : IDL.Text, 'count' : IDL.Nat }))],
        ['query'],
      ),
    'getOwnerInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getOwnerNotifications' : IDL.Func([], [IDL.Vec(Notification)], ['query']),
    'getProperties' : IDL.Func([], [IDL.Vec(Property)], ['query']),
    'getProperty' : IDL.Func([IDL.Nat], [IDL.Opt(Property)], ['query']),
    'getPropertyBookings' : IDL.Func([IDL.Nat], [IDL.Vec(Booking)], ['query']),
    'getReports' : IDL.Func([], [IDL.Vec(Report)], ['query']),
    'getReviews' : IDL.Func([IDL.Nat], [IDL.Vec(Review)], ['query']),
    'getStripePayments' : IDL.Func([], [IDL.Text], []),
    'getStripeSessionStatus' : IDL.Func([IDL.Text], [StripeSessionStatus], []),
    'getUnreadNotificationCount' : IDL.Func([], [IDL.Nat], ['query']),
    'getUserBookings' : IDL.Func(
        [IDL.Principal],
        [IDL.Vec(Booking)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'getWishlist' : IDL.Func([], [IDL.Vec(IDL.Nat)], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'isStripeConfigured' : IDL.Func([], [IDL.Bool], ['query']),
    'isUserBlocked' : IDL.Func([IDL.Principal], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'listProperty' : IDL.Func([Property], [], []),
    'markAllNotificationsRead' : IDL.Func([], [], []),
    'markNotificationRead' : IDL.Func([IDL.Nat], [], []),
    'removeFromWishlist' : IDL.Func([IDL.Nat], [], []),
    'requestApproval' : IDL.Func([], [], []),
    'resolveReport' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'setStripeConfiguration' : IDL.Func([StripeConfiguration], [], []),
    'submitReport' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text], [], []),
    'trackActivity' : IDL.Func([], [], []),
    'trackPropertyView' : IDL.Func([IDL.Nat], [], []),
    'transform' : IDL.Func(
        [TransformationInput],
        [TransformationOutput],
        ['query'],
      ),
    'unblockUser' : IDL.Func([IDL.Principal], [], []),
    'updateInquiryStatus' : IDL.Func(
        [
          IDL.Nat,
          IDL.Variant({ 'rejected' : IDL.Null, 'accepted' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateProperty' : IDL.Func([IDL.Nat, Property], [], []),
    'verifyProperty' : IDL.Func([IDL.Nat], [], []),
  });
};

export const init = ({ IDL }) => { return []; };