/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Address {
  'blocknumber' : string,
  'street' : string,
  'country' : string,
  'city' : string,
  'state' : string,
  'bluenumber' : string,
}
export interface Announcement {
  'id' : bigint,
  'title' : string,
  'expiresAt' : [] | [Time],
  'createdAt' : Time,
  'isActive' : boolean,
  'message' : string,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Booking {
  'id' : bigint,
  'status' : { 'cancelled' : null } |
    { 'pending' : null } |
    { 'paid' : null } |
    { 'rejected' : null },
  'endDate' : Time,
  'propertyId' : bigint,
  'userDetails' : { 'name' : string, 'email' : string, 'phone' : string },
  'propertyIdText' : string,
  'student' : Principal,
  'stripeSessionId' : [] | [string],
  'totalPrice' : bigint,
  'startDate' : Time,
}
export interface Coordinates { 'lat' : string, 'lang' : string }
export type ExternalBlob = Uint8Array;
export interface Inquiry {
  'id' : bigint,
  'status' : { 'pending' : null } |
    { 'rejected' : null } |
    { 'accepted' : null },
  'studentName' : string,
  'inquiryType' : { 'bookVisit' : null } |
    { 'contactOwner' : null },
  'studentPrincipal' : Principal,
  'studentPhone' : string,
  'propertyId' : bigint,
  'message' : string,
  'timestamp' : Time,
}
export interface Notification {
  'id' : bigint,
  'ownerPrincipal' : Principal,
  'relatedInquiryId' : [] | [bigint],
  'isRead' : boolean,
  'message' : string,
  'timestamp' : Time,
}
export interface Property {
  'id' : bigint,
  'title' : string,
  'verified' : boolean,
  'owner' : Principal,
  'description' : string,
  'amenities' : Array<string>,
  'availableFrom' : Time,
  'viewCount' : bigint,
  'approved' : boolean,
  'genderPreference' : { 'boys' : null } |
    { 'unisex' : null } |
    { 'girls' : null },
  'address' : Address,
  'pricePerMonth' : bigint,
  'roomType' : { 'apartment' : null } |
    { 'sharedRoom' : null } |
    { 'single' : null },
  'photos' : Array<ExternalBlob>,
  'coordinates' : Coordinates,
  'contactPhone' : string,
}
export interface Report {
  'id' : bigint,
  'status' : { 'resolved' : null } |
    { 'pending' : null } |
    { 'dismissed' : null },
  'targetPropertyId' : bigint,
  'description' : string,
  'reporterId' : Principal,
  'timestamp' : Time,
  'actionTaken' : [] | [string],
  'reason' : string,
}
export interface Review {
  'propertyId' : bigint,
  'comment' : string,
  'timestamp' : Time,
  'student' : Principal,
  'rating' : bigint,
}
export interface ShoppingItem {
  'productName' : string,
  'currency' : string,
  'quantity' : bigint,
  'priceInCents' : bigint,
  'productDescription' : string,
}
export interface StripeConfiguration {
  'allowedCountries' : Array<string>,
  'secretKey' : string,
}
export type StripeSessionStatus = {
    'completed' : { 'userPrincipal' : [] | [string], 'response' : string }
  } |
  { 'failed' : { 'error' : string } };
export type Time = bigint;
export interface TransformationInput {
  'context' : Uint8Array,
  'response' : http_request_result,
}
export interface TransformationOutput {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export interface UserProfile {
  'name' : string,
  'role' : { 'admin' : null } |
    { 'owner' : null } |
    { 'student' : null },
  'email' : string,
  'phone' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface http_header { 'value' : string, 'name' : string }
export interface http_request_result {
  'status' : bigint,
  'body' : Uint8Array,
  'headers' : Array<http_header>,
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addReview' : ActorMethod<[bigint, bigint, string], undefined>,
  'addToWishlist' : ActorMethod<[bigint], undefined>,
  'approveProperty' : ActorMethod<[bigint], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'blockUser' : ActorMethod<[Principal], undefined>,
  'bookProperty' : ActorMethod<[Booking], undefined>,
  'cancelBooking' : ActorMethod<[bigint], undefined>,
  'confirmBooking' : ActorMethod<[bigint], undefined>,
  'rejectBooking' : ActorMethod<[bigint], undefined>,
  'createAnnouncement' : ActorMethod<[string, string, [] | [Time]], undefined>,
  'createCheckoutSession' : ActorMethod<
    [Array<ShoppingItem>, string, string],
    string
  >,
  'createInquiry' : ActorMethod<
    [
      bigint,
      string,
      string,
      { 'bookVisit' : null } |
        { 'contactOwner' : null },
      string,
    ],
    undefined
  >,
  'deactivateAnnouncement' : ActorMethod<[bigint], undefined>,
  'deleteProperty' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[bigint, Principal], undefined>,
  'dismissReport' : ActorMethod<[bigint], undefined>,
  'getActiveAnnouncements' : ActorMethod<[], Array<Announcement>>,
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getAnalyticsSummary' : ActorMethod<
    [],
    {
      'pendingListings' : bigint,
      'totalProperties' : bigint,
      'activeListings' : bigint,
      'totalReports' : bigint,
      'totalBookings' : bigint,
      'totalUsers' : bigint,
      'totalInquiries' : bigint,
    }
  >,
  'getApprovedProperties' : ActorMethod<[], Array<Property>>,
  'getBookings' : ActorMethod<[], Array<Booking>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getDailyActiveUserCounts' : ActorMethod<
    [],
    Array<{ 'date' : string, 'count' : bigint }>
  >,
  'getOwnerInquiries' : ActorMethod<[], Array<Inquiry>>,
  'getOwnerNotifications' : ActorMethod<[], Array<Notification>>,
  'getProperties' : ActorMethod<[], Array<Property>>,
  'getProperty' : ActorMethod<[bigint], [] | [Property]>,
  'getPropertyBookings' : ActorMethod<[bigint], Array<Booking>>,
  'getReports' : ActorMethod<[], Array<Report>>,
  'getReviews' : ActorMethod<[bigint], Array<Review>>,
  'getStripePayments' : ActorMethod<[], string>,
  'getStripeSessionStatus' : ActorMethod<[string], StripeSessionStatus>,
  'getUnreadNotificationCount' : ActorMethod<[], bigint>,
  'getUserBookings' : ActorMethod<[Principal], Array<Booking>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'getWishlist' : ActorMethod<[], Array<bigint>>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'isStripeConfigured' : ActorMethod<[], boolean>,
  'isUserBlocked' : ActorMethod<[Principal], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'listProperty' : ActorMethod<[Property], undefined>,
  'markAllNotificationsRead' : ActorMethod<[], undefined>,
  'markNotificationRead' : ActorMethod<[bigint], undefined>,
  'removeFromWishlist' : ActorMethod<[bigint], undefined>,
  'requestApproval' : ActorMethod<[], undefined>,
  'resolveReport' : ActorMethod<[bigint, string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'setStripeConfiguration' : ActorMethod<[StripeConfiguration], undefined>,
  'submitReport' : ActorMethod<[bigint, string, string], undefined>,
  'trackActivity' : ActorMethod<[], undefined>,
  'trackPropertyView' : ActorMethod<[bigint], undefined>,
  'transform' : ActorMethod<[TransformationInput], TransformationOutput>,
  'unblockUser' : ActorMethod<[Principal], undefined>,
  'updateInquiryStatus' : ActorMethod<
    [bigint, { 'rejected' : null } | { 'accepted' : null }],
    undefined
  >,
  'updateProperty' : ActorMethod<[bigint, Property], undefined>,
  'verifyProperty' : ActorMethod<[bigint], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];